[package]
name = "raytr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.3"
nalgebra = "0.30.1"
rand = { version = "0.8.4", features = ["small_rng"] }
